language: android
jdk: oraclejdk8
sudo: false
os: linux
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - build-tools-27.0.3
    - android-27
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
  licenses:
    - android-sdk-preview-license-.+
    - android-sdk-license-.+
    - google-gdk-license-.+
script:
  - ./gradlew clean build ci
before_install:
  - yes | sdkmanager "platforms;android-27"
env:
  global:
    - BINTRAY_USER="quanturium"
    - secure: "fqo8Jm1JDqGDFLjXA2D53k+rbLOk5gG3Jc6ozK/a2rP1Kn2JZRFXoIiBvfj/2yDW7yhuu1pCy3GGQbz8SiPfhBfTxCx+gCNIOPIK/6RGk8ea6tjECCAXasA9Repv/6hzmO7heDO4OepC5c8+3J8zic3bQredMeqbGMu3T2oInhidOjqPWRGfkvKXSbpeZvH3d2VfcnPbpAXEsrOgvtyo3IE5d14mQxcheYmBGXznbF51zRpqZbRFcf32cu8hgth9bZEihL0mYkKbHHmhvMt55Ux+hnFaCTWrB19wZRJD8oWOrX/Rw9JPG8+vwuMcv3wc6xyvuasapLs8I28sEhWzeg4CTGvX3JG2hFiCYSKmTpshGRSSRPalLNr3wOWpKZTwpE0Gh/6RmjSCnnE4YHhJEL9nPZQNLWTQs7Vt4bieByh9ZGz520giSUgQ8x1KUEKxP4sdwsrNlCS56zEbgloQ0BQuEDFYwxNZ+UdBg3nM6IGLBcDXD1DeWFB3gdoJdvgdAJzb/k5TRhHRG5hN9HExYuWmOS6DRaI+OjRrLeti70Z1gZw0KZ+kbYYUKSdcs8x+4oG8rtE1LpbDgcdK8w+UFbfY4hlNG/O3tA8xpsAokGgw1zUCDl/8juf7vk/+BNJcKvRW8zzlpHN81ltmmXobyeRSFcllNvZF+pmsBeWxtoE="
